package com.convocatis.app.database.entity

data class ProfileEntity(
    var email: String? = null,
    var name: String? = null,
    var surname: String? = null,
    var nick: String? = null,
    var syncTime: Long? = null,
    var notificationsEnabled: Boolean = true,
    var otherDenominationsEnabled: Boolean = false,
    var uiLangId: Long? = null,
    var myLanguagesIds: String? = null,
    var myServerLanguagesIds: String? = null,
    var denominationId: Long? = null,
    var themeId: Long? = null,
    var emailDirty: Boolean = false,
    var nameSurnameNickDirty: Boolean = false,
    var syncTimeDirty: Boolean = false,
    var notificationsEnabledDirty: Boolean = false,
    var otherDenominationsEnabledDirty: Boolean = false,
    var uiLangIdDirty: Boolean = false,
    var denominationIdDirty: Boolean = false,
    var themeIdDirty: Boolean = false,
    var loggedIn: Boolean = false,
    var id: Long? = null,
    var verified: Int = 0,
    var hasNews: Int = 0,
    var invString: String? = null,
    var authService: Int? = null,
    var sponsor: Int? = null
)
